cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.CartAdd.as_view(), name='add_to_cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_detail'),
    path('remove_one_item/', views.CartRemoveOneItem.as_view(),
         name='cart_remove_one_item'),
    path('remove/', views.CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # allauth
    path('accounts/', include('allauth.urls')),

    # apps
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('shop.urls', namespace='shop')),



    # rest framework
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('shop.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # debug toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/', views.CheckoutFormView.as_view(), name='checkout'),
    path('history/', views.OrderHistoryView.as_view(), name='history'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>/', views.ProductsByCategory.as_view(), name='products_by_category'),
    path('detail/<int:pk>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='homepage'),
]

cart/views.py
import json
from decimal import Decimal

from django.shortcuts import get_object_or_404
from django.views.generic.base import View, TemplateView
from django.http import JsonResponse
from .cart import Cart
from shop.models import Product


class CartAdd(View):
    def post(self, request):
        body_data = json.loads(request.body.decode('utf-8'))
        cart = Cart(request)
        product = get_object_or_404(Product, id=body_data.get('product_id'))
        cart.add(product=product)
        product_subtotal = cart.cart[str(product.id)]['quantity'] * Decimal(cart.cart[str(product.id)]['price'])
        return JsonResponse({
            'total_cart_qty': cart.__len__(),
            'subtotal': product_subtotal,
            'cart_total': cart.get_total_price()
        })


class CartDetail(TemplateView):
    template_name = 'cart/cart_detail.html'


class CartRemoveOneItem(View):
    def post(self, request):
        body_data = json.loads(request.body.decode('utf-8'))
        cart = Cart(request)
        product = get_object_or_404(Product, id=body_data.get('product_id'))
        cart.remove_one_item(product)
        product_subtotal = cart.cart[str(product.id)]['quantity'] * Decimal(cart.cart[str(product.id)]['price'])
        return JsonResponse({
            'total_cart_qty': cart.__len__(),
            'cart_total': cart.get_total_price(),
            'subtotal': product_subtotal,
        })


class CartRemove(View):
    def post(self, request):
        body_data = json.loads(request.body.decode('utf-8'))
        cart = Cart(request)
        product = get_object_or_404(Product, id=body_data.get('product_id'))
        cart.remove(product)
        return JsonResponse({
            'total_cart_qty': cart.__len__(),
            'cart_total': cart.get_total_price()
        })

templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
    <title>Your Cart</title>
{% endblock title %}

{% block content %}

    <main class="mt-5 pt-4">
        <div class="container mt-5">
            <div class="table-responsive">
                <h2>Your Cart:</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Product</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Unit Price</th>
                        <th scope="col">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item  in cart %}
                        {% with item.product as product %}
                            <tr data-index={{ product.id }}>
                                <th data-index={{ product.id }} scope="row">{{ forloop.counter }}</th>
                                <td>
                                    {% if product.image.url %}
                                        <a href="{{ product.image.url }}">
                                            <img src="{% thumbnail product.image 50x0 %}">
                                        </a>
                                    {% endif %}
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </td>
                                <td>
                                    <button id="remove-product-btn" type="submit" class="btn-sm btn-outline border-0 mr-1 remove-btn" aria-hidden="true" data-index={{ product.id }}><i
                                            class="fas fa-minus" aria-hidden="true" ></i></button>
                                    <span class="product-qty">{{ item.quantity }}</span>
                                    <button id="add-product-btn" type="submit" class="btn-sm btn-outline border-0 ml-1 add-btn" aria-hidden="true" data-index={{ product.id }}><i
                                            class="fas fa-plus " aria-hidden="true" data-index={{ product.id }}></i></button>
                                </td>

                                <td>${{ item.price }}</td>
                                <td class="product-subtotal">${{ item.total_price }}</td>
                                <td><span>
                                    <button data-index={{ product.id }} class="remove-btn-can" style="border: none;
                                      background-color: transparent;
                                      outline: none;"><i class="fas fa-trash ml-3"></i>
                                    </button>
                                </span>


                                </td>
                            </tr>
                        {% endwith %}
                    {% empty %}
                        <tr>
                            <td colspan="4"></td>
                            <td><b>Your cart is empty</b></td>
                        </tr>

                    {% endfor %}
                    <tr>
                        <td><b>Total:</b></td>
                        <td colspan="3"></td>
                        <td id="cart-total"><b>${{ cart.get_total_price }}</b></td>
                    </tr>

                    </tbody>
                </table>

                <p class="text-right">
                    <a href="{% url "shop:homepage" %}" class="btn btn-secondary">
                        Continue shopping</a>
                    {% if cart|length %}
                        <a href="{% url 'order:checkout' %}" class="btn btn-primary">Checkout</a>
                        </p>
                    {% endif %}
            </div>
        </div>
    </main>

{% endblock content %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/shop/fetch-request.js' %}"></script>
    <script>
        const headers = {
            'Content-Type': 'application/json',
            'X-CSRFToken': "{{ csrf_token }}"
        }

        // this button removes 1pc of product from the cart
        // if the number of products after deletion is zero, it completely removes the product from the cart
        document.querySelectorAll('.remove-btn').forEach(function (item) {
            item.addEventListener('click', function () {
            let product_id = this.dataset.index
            let remove_one_item_url = "{% url 'cart:cart_remove_one_item' %}"
            let remove_product_url = "{% url 'cart:cart_remove' %}"
            let product_qty = item.nextElementSibling.textContent

            if (product_qty <= 1) {
                sendRequest('POST', remove_product_url, {'product_id': product_id}, headers)
                .then(function (data) {
                    item.parentElement.parentElement.remove()
                    document.querySelector('#cart-total').innerHTML = '$' + data.cart_total
                    document.querySelector('#total-cart-qty').innerHTML = data.total_cart_qty

                    })
                .catch(err => console.log(err))
            } else {
                sendRequest('POST', remove_one_item_url, {'product_id': product_id}, headers)
                .then(function (data) {
                    item.nextElementSibling.textContent = parseInt(item.nextElementSibling.textContent) - 1
                    document.querySelector('#cart-total').innerHTML = '$' + data.cart_total
                    document.querySelector('#total-cart-qty').innerHTML = data.total_cart_qty
                    item.closest('tr').querySelector('.product-subtotal').innerHTML = '$' + data.subtotal
                    })
                .catch(err => console.log(err))

            }

        })
        })

        // this button adds 1pc of product to the cart
        document.querySelectorAll('.add-btn').forEach(function (item) {
            item.addEventListener('click', function () {
            let product_id = this.dataset.index
            let add_item_url = "{% url 'cart:add_to_cart' %}"

            sendRequest('POST', add_item_url, {'product_id': product_id}, headers)
            .then(function (data) {
                console.log(item)
                item.previousElementSibling.textContent = parseInt(item.previousElementSibling.textContent) + 1
                document.querySelector('#total-cart-qty').innerHTML = data.total_cart_qty
                item.closest('tr').querySelector('.product-subtotal').innerHTML = '$' + data.subtotal
                document.querySelector('#cart-total').innerHTML = '$' + data.cart_total
                console.log(data.cart_total)
            })
            .catch(err => console.log(err))
        })
            }

        )

        // removing product from the cart with all its pc's
        document.querySelectorAll('.remove-btn-can').forEach(function (item) {
            item.addEventListener('click', function () {
                let product_id = this.dataset.index
                let remove_product_url = "{% url 'cart:cart_remove' %}"

                sendRequest('POST', remove_product_url, {'product_id': product_id}, headers)
                    .then(function (data) {
                        item.closest('tr').remove()
                        document.querySelector('#cart-total').innerHTML = '$' + data.cart_total
                        document.querySelector('#total-cart-qty').innerHTML = data.total_cart_qty

                    })
                    .catch(err => console.log(err))


            })
        })


    </script>
{% endblock %}

  