cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.CartAdd.as_view(), name='add_to_cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_detail'),
    path('remove_one_item/', views.CartRemoveOneItem.as_view(),
         name='cart_remove_one_item'),
    path('remove/', views.CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # allauth
    path('accounts/', include('allauth.urls')),

    # apps
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('shop.urls', namespace='shop')),



    # rest framework
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('shop.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # debug toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

shop/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='api_product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='api_product_detail'),
    path('cart/', views.CartDetailView.as_view(), name='api_cart'),
    path('order/create/', views.OrderCreateView.as_view(), name='api_order_create'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>/', views.ProductsByCategory.as_view(), name='products_by_category'),
    path('detail/<int:pk>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='homepage'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:products_by_category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    LABEL_CHOICES = (
        ('N', 'new'),
        ('B', 'bestseller'),
        ('NON', 'not applicable')
    )

    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.jpg')
    is_available = models.BooleanField(default=True)
    is_on_stock = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, related_name='created_products', on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=5, default='N')

    class Meta:
        ordering = ('-created_at',)
        index_together = ('id', 'slug')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'pk': self.pk, 'slug': self.slug})

shop/api/views.py
from rest_framework import generics
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions

from .serializers import ProductSerializer, OrderSerializer
from shop.models import Product
from order.models import OrderItem, Order
from cart.cart import Cart


class ProductListView(generics.ListAPIView):
    queryset = Product.objects.filter(is_available=True)
    serializer_class = ProductSerializer


class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.filter(is_available=True)
    serializer_class = ProductSerializer


class CartDetailView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request):
        cart = request.session.get('cart')
        return Response(cart)


class OrderCreateView(CreateAPIView):
    cart = None
    serializer_class = OrderSerializer
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, *args, **kwargs):
        self.cart = Cart(request)
        if self.cart:
            return self.create(request, *args, **kwargs)
        else:
            return Response(status=403)

    def perform_create(self, serializer):
        obj = serializer.save(user=self.request.user)
        for item in self.cart:
            OrderItem.objects.create(order=obj,
                                     product=item['product'],
                                     price=item['price'],
                                     quantity=item['quantity'])

shop/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.conf import settings

from .models import Category, Product

r = settings.R


class AvailabilityMixin:
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(is_available=True)


class HomePageView(AvailabilityMixin, ListView):
    queryset = Product.objects.all()
    context_object_name = 'products'
    template_name = 'shop/homepage.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['categories'] = Category.objects.all()
        return context


class ProductDetailView(AvailabilityMixin, DetailView):
    model = Product
    template_name = 'shop/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_product_purchases'] = r.get(
            f'product:{self.get_object().id}:num_of_purchases')
        return context


class ProductsByCategory(HomePageView):
    template_name = 'shop/product_list.html'

    def get_queryset(self):
        return super(ProductsByCategory, self).get_queryset().filter(category__slug=self.kwargs.get('category_slug'))

templates/shop/homepage.html
{% extends 'base.html' %}

{% block content %}

    <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
            <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        <!--Slides-->
        <div class="carousel-inner" role="listbox">

            <!--First slide-->
            <div class="carousel-item active">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                    </div>
                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/First slide-->

            <!--Second slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
                    </div>

                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/Second slide-->

            <!--Third slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
                    </div>
                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/Third slide-->

        </div>
        <!--/.Slides-->

        <!--Controls-->
        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->

    </div>
    <!--/.Carousel Wrapper-->
    <main>
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">

                        <a class="nav-link" href="{% url 'shop:homepage' %}">All
                        </a>
                        {% for category in categories %}
                            {% if category == category_current %}
                                <li class="nav-item active">
                                    <span class="sr-only">(current)</span>
                                    {% else %}
                                <li class="nav-item">
                            {% endif %}
                            <a class="nav-link"
                               href="{% url 'shop:products_by_category' category.slug %}">{{ category.name }}</a>
                        {% endfor %}

                    </ul>
                    <!-- Links -->


                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center mb-4">

                <!--Grid row-->
                <div class="row wow fadeIn">

                    <!--Grid column-->
                    {% for product in products %}
                        <div class="col-lg-3 col-md-6 mb-4">
                            {% include 'shop/product_card.html' %}
                        </div>

                    {% endfor %}

                </div>


            </section>
            <!--Section: Products v.3-->

        </div>
    </main>
{% include 'footer.html' %}
{% endblock %}

templates/shop/product_card.html
<div class="card">

    <!--Card image-->
    <div class="view overlay">
        <img src="{{ product.image.url }}" class="card-img-top"
             alt="">
        <a href={{ product.get_absolute_url }}>
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>
    <!--Card image-->

    <!--Card content-->
    <div class="card-body text-center">
        <!--Category & Title-->
        <a href="" class="grey-text">
            <h5>{{ product.category }}</h5>
        </a>
        <h5>
            <strong>
                <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.name }}
                    <span class="badge badge-pill danger-color">{{ product.get_label_display }}</span>
                </a>
            </strong>
        </h5>

        <h4 class="font-weight-bold blue-text">
            {% if product.discount_price %}
                <span class="text-danger"><strong><del>{{ product.price }}$</del></strong></span>
                <strong>{{ product.discount_price }}</strong>
            {% else %}
                <strong>{{ product.price }}</strong>
            {% endif %}
        </h4>
    </div>
    <!--Card content-->
</div>

templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{{ product.image.url }}" class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="">
                                <span class="badge purple mr-1">{{ product.category }}</span>
                            </a>
                        </div>

                        <p class="lead">
                            {% if product.discount_price %}
                                <span class="mr-1 text-danger">
                                <del>${{ product.price }}</del>
                                </span>
                                <span>${{ product.discount_price }}</span>
                            {% else %}
                                <span>${{ product.price }}</span>
                            {% endif %}

                        </p>
                        <p class="lead font-weight-bold">{{ product.name }}</p>
                        <div style="height: 100px;">
                            <p class="h-100">{{ product.description|truncatechars_html:200 }}</p>
                        </div>
                        {% if product.id|slugify not in cart.cart.keys %}
                            <button id="add_to_cart_btn" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </button>
                        {% else %}
                            <button class="btn btn-secondary btn-md my-0 p" type="submit" disabled>Already added
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </button>
                        {% endif %}
                        <div class="mt-3">
                            <i class="fas fa-shopping-cart pr-1" data-toggle="tooltip" title="total purchases"></i>{{ total_product_purchases|add:"0" }}
                        </div>
                    </div>
                    <!--Content-->
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
            <hr>
            <!--Grid row-->
            <div class="row d-flex justify-content-center wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 text-center">

                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                        odit
                        voluptates,
                        quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/shop/fetch-request.js' %}"></script>
    <script>
        let url = "{% url 'cart:add_to_cart' %}"

        const headers = {
            'Content-Type': 'application/json',
            'X-CSRFToken': "{{ csrf_token }}"
        }
        let a = document.querySelector('#add_to_cart_btn')
        a.onclick = function (event) {
            sendRequest('POST', url, {'product_id': {{ product.id }}}, headers)
                .then(function (data) {
                    document.querySelector('#total-cart-qty').innerHTML = data.total_cart_qty
                    document.querySelector('#add_to_cart_btn').setAttribute("disabled", "disabled")
                    document.querySelector('#add_to_cart_btn').innerHTML = 'Already added' +
                        '<i class="fas fa-shopping-cart ml-1"></i>'
                })
                .catch(err => console.log(err))
        }

        $(document).ready(function () {
            $("[data-toggle=tooltip]").tooltip({ placement: 'bottom'});
        })
    </script>
{% endblock %}

templates/shop/product_list.html
{% extends 'base.html' %}

{% block content %}

    <main class="mt-5 pt-4">
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">

                        <a class="nav-link" href="{% url 'shop:homepage' %}">All
                        </a>
                        {% for category in categories %}
                            {% if category == category_current %}
                                <li class="nav-item active">
                                    <span class="sr-only">(current)</span>
                                    {% else %}
                                <li class="nav-item">
                            {% endif %}
                            <a class="nav-link"
                               href="/">{{ category.name }}</a>
                        {% endfor %}

                    </ul>
                    <!-- Links -->


                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center mb-4">

                <!--Grid row-->
                <div class="row wow fadeIn">

                    <!--Grid column-->
                    {% for product in products %}
                        <div class="col-lg-3 col-md-6 mb-4">
                            {% include 'shop/product_card.html' %}
                        </div>

                    {% endfor %}

                </div>


            </section>
            <!--Section: Products v.3-->

        </div>
    </main>

{% endblock %}