cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.CartAdd.as_view(), name='add_to_cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_detail'),
    path('remove_one_item/', views.CartRemoveOneItem.as_view(),
         name='cart_remove_one_item'),
    path('remove/', views.CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # allauth
    path('accounts/', include('allauth.urls')),

    # apps
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('shop.urls', namespace='shop')),



    # rest framework
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('shop.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # debug toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/', views.CheckoutFormView.as_view(), name='checkout'),
    path('history/', views.OrderHistoryView.as_view(), name='history'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>/', views.ProductsByCategory.as_view(), name='products_by_category'),
    path('detail/<int:pk>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='homepage'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css'%}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>
<body>

{% include 'navbar.html' %}


{% if messages %}
    <div class="mt-5 pt-4">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endfor %}
    </div>
{% endif %}




{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js'%}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js'%}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

{% block extra_js %}
{% endblock %}

</body>

</html>

templates/footer.html
<footer class="page-footer text-center font-small mb-n5 wow fadeIn position-relative">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'shop:homepage' %}">
            <strong class="blue-text">My Shop</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="d-flex collapse navbar-collapse justify-content-end" id="navbarSupportedContent">

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                <li class="nav-item">
                    <a href="{% url "cart:cart_detail" %}" class="nav-link waves-effect">
                        {% with cart|length as total_items %}
                            <span id="total-cart-qty" class="badge red z-depth-1 mr-1">{{ total_items }}</span>
                        {% endwith %}
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'order:history' %}" class="nav-link waves-effect">
                            <span class="clearfix d-none d-sm-inline-block"> My Orders </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account_logout' %}" class="nav-link waves-effect">
                            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'account_login' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Sign Up </span>
                    </a>
                </li>
                {% endif %}


            </ul>


        </div>

    </div>
</nav>