cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.CartAdd.as_view(), name='add_to_cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_detail'),
    path('remove_one_item/', views.CartRemoveOneItem.as_view(),
         name='cart_remove_one_item'),
    path('remove/', views.CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # allauth
    path('accounts/', include('allauth.urls')),

    # apps
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('shop.urls', namespace='shop')),



    # rest framework
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('shop.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # debug toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

coupon/urls.py
from django.urls import path

from . import views

app_name = 'coupon'

urlpatterns = [
    path('apply/', views.CouponApply.as_view(), name='apply'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/', views.CheckoutFormView.as_view(), name='checkout'),
    path('history/', views.OrderHistoryView.as_view(), name='history'),
]

order/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from coupon.models import Coupon
from shop.models import Product


class Order(models.Model):
    user = models.ForeignKey(User,
                             related_name='orders', on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    address_optional = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100))


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

order/forms.py
import re

from django import forms

from order.models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['city', 'address', 'address_optional', 'postal_code']
        widgets = {
            'city': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
                'placeholder': 'Moscow'
            }),
            'address': forms.TextInput(attrs={
                'placeholder': 'Stroiteley d.3'
            })
        }

    def clean_address(self):
        address = self.cleaned_data['address']
        if not re.search(r'\d', address):
            self.add_error('address', 'Address must have at least 1 digit')
        return address

    def clean_postal_code(self):
        postal_code = self.cleaned_data['postal_code']
        if not re.match(r'^[1-9]\d{5}$', postal_code):
            self.add_error('postal_code', 'Please provide a valid postal code')
        return postal_code

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import FormView, ListView

from cart.cart import Cart
from coupon.forms import CouponApplyForm
from order.forms import OrderCreateForm
from order.models import OrderItem, Order


class CheckoutFormView(LoginRequiredMixin, FormView):
    form_class = OrderCreateForm
    template_name = 'order/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_coupon"] = CouponApplyForm()
        return context

    def post(self, *args, **kwargs):
        cart = Cart(self.request)
        form = self.get_form()
        if form.is_valid() and len(cart):
            order = form.save(commit=False)
            order.user = self.request.user
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            self.request.session['order_id'] = order.id
            return redirect('payment:process')
        return redirect('order:checkout')


class OrderHistoryView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'order/order_history.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return super(OrderHistoryView, self).get_queryset().filter(user=self.request.user).order_by(
            '-id').prefetch_related('items', 'items__product')

templates/order/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Checkout</title>
{% endblock title %}
{% block content %}<!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Checkout form</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Card-->
                    <div class="card">


                        <!--Card content-->

                            <form method="post" class="card-body">
                                {{ form|crispy }}
                                <p><input type="submit" class="btn btn-primary" value="Place order"></p>
                                {% csrf_token %}
                            </form>


                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">

                    <!-- Heading -->
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        {% comment %} <span class="badge badge-secondary badge-pill">3</span> {% endcomment %}
                    </h4>

                    <!-- Cart -->
                    <ul class="list-group mb-3 z-depth-1">
                        {% for item in cart %}
                            {% with item.product as product %}
                                <li class="list-group-item d-flex justify-content-between lh-condensed">
                                    <div>
                                        <h6 class="my-0">{{ product.name }} X {{ item.quantity }}</h6>
                                        <small class="text-muted">{{ product.description|truncatechars_html:20 }}</small>
                                    </div>
                                    <span class="text-muted">${{ item.total_price }}</span>
                                </li>
                            {% endwith %}
                        {% endfor %}

                        {% if cart.coupon %}

                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <div class="text-success">
                                    <h6 class="my-0">Promo code</h6>
                                    <small>{{ cart.coupon.code }}</small>
                                </div>
                                <span class="text-success">-${{ cart.get_discount|floatformat:2 }}</span>
                            </li>
                        {% endif %}


                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>${{ cart.get_total_price_after_discount|floatformat:2 }}</strong>
                        </li>

                    </ul>

                    <form class="card p-2" action="{% url 'coupon:apply' %}" method='post'>
                        <div class="input-group">
                            {{ form_coupon.code }}
                            {% csrf_token %}
                            {% comment %} <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2" value="{{ form_coupon.code }}"> {% endcomment %}
                            <div class="input-group-append">
                                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                            </div>
                        </div>
                    </form>

                    <!-- Cart -->

                    <!-- Promo code -->

                    <!-- Promo code -->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->

{% endblock content %}

templates/order/order_history.html
{% extends 'base.html' %}
{% block title %}
    My Orders
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 100px;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Order №</th>
                <th scope="col">Order Date</th>
                <th scope="col">Amount</th>
                <th scope="col">Paid Status</th>
                <th scope="col">Order Details</th>
            </tr>
            </thead>
            <tbody>
            {% for order  in orders %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ order.id }}</td>
                    <td>{{ order.created.date }}</td>
                    <td>{{ order.get_total_cost }}</td>
                    <td>
                        {% if order.paid %}Оплачено{% else %}Не оплачено{% endif %}
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button
                                type="button"
                                class="btn btn-primary modal-btn"
                                data-mdb-toggle="modal"
                                data-mdb-target="#exampleModal{{ order.id }}"
                        >
                            Show Details
                        </button>

                        <!-- Modal -->
                        <div
                                class="modal fade"
                                id="exampleModal{{ order.id }}"
                                tabindex="-1"
                                aria-labelledby="exampleModalLabel"
                                aria-hidden="true"
                        >
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Order details #{{ order.id }}</h5>
                                    </div>
                                    <div class="modal-body">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Product</th>
                                                <th scope="col">Price</th>
                                                <th scope="col">Total Price</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.items.all  %}
                                                    <tr>
                                                        <th>{{ forloop.counter }}</th>
                                                        <th>{{ item.product }} X {{ item.quantity }}</th>
                                                        <th>{{ item.price }}</th>
                                                        <th>{{ item.get_cost }}</th>
                                                    </tr>
                                                {% endfor %}
                                                <tr>
                                                    <th><b>Total:</b></th>
                                                    <th colspan="2"></th>
                                                    <th><b>${{ order.get_total_cost }}</b></th>
                                                </tr>

                                            </tbody>
                                        </table>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary modal-btn-close" data-mdb-dismiss="modal">
                                            Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4"></td>
                    <td><b>You have no orders yet.</b></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

{% block extra_js %}
    <script>

        $('.modal-btn').on('click', function() {
            const btm_modal_attr = this.getAttribute('data-mdb-target')
            $(btm_modal_attr).modal('show');})

        $('.modal-btn-close').on('click', function() {
            $('.modal').modal('hide');})


        {#document.querySelectorAll('.modal').forEach(function(item) {#}
            {#item.addEventListener('click', function(){#}
            {#    item.nextElementSibling.show()#}
        {#    item.show()#}
        {#document.querySelector('.modal').modal('show')#}
    </script>
{% endblock %}